Base commit
pahoma/event-appointments pull request #1
Opened 2023-10-05 21:56 UTC by pahoma

2023-10-06 07:00 UTC, sokyrko commented on README.md
> -Event appointment service
This readme has some rendering issues, see [here](https://github.com/pahoma/event-appointments/blob/95154f1182f8a177eca6f6b5e4f9f8e4936cb691/README.md).
Check the header and endpoints.

2023-10-06 07:00 UTC, sokyrko commented on README.md
> +- **Database Initialization**: Set up your database connection and execute migrations with ease.
IMHO, db initialization by user-facing CLI is weird.

2023-10-06 07:00 UTC, sokyrko commented on README.md
> +- `Init`: Initializes the connection to the database and executes migrations.
Commands really start with uppercase letter?

2023-10-06 07:00 UTC, sokyrko commented on README.md
> +    - `Delete`: Deletes a specified appointment. Provide the IDs of the appointments to delete using the `-uuids` flag.
If you use clap, you have double dash `--` for flags, I think.
It looks like this part of the doc was corrupted by Google Docs or something

2023-10-06 07:00 UTC, sokyrko commented on migrations/20230930132154_init.sql
> +    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
Inconsistent casing for column names here.
`createdAt`, `short_url`.

2023-10-06 07:00 UTC, sokyrko commented on web_server/tests/api/main.rs
> +        assert!(true);
Yay, it works =)

2023-10-06 07:00 UTC, sokyrko commented on web_server/tests/api/helpers.rs
> +        configuration.qr_client.api_url.clone(),
It looks like you don't need `clone` here, the object is owned and values can be moved.

2023-10-06 07:00 UTC, sokyrko commented on web_server/src/startup.rs
> +                   web::get().to(|| async { HttpResponse::Ok().body("/") })
What is this route for? Is it `/status` ?

2023-10-06 07:00 UTC, sokyrko commented on web_server/src/routes/validation.rs
> +    println!("{} {} {}",  invitation.date.date(), yesterday.date(), invitation.date < yesterday);
`tracing::info!`

2023-10-06 07:00 UTC, sokyrko commented on web_server/src/routes/validation.rs
> +            HttpResponse::PermanentRedirect()
Why would `validate_invitation_by_id` return a redirect in API?

2023-10-06 07:00 UTC, sokyrko commented on web_server/src/routes/validation.rs
> +                .append_header((http::header::LOCATION, invitation.link.unwrap().into_inner()))
Please use `expect()` to clarify why `unwrap` is safe.

2023-10-06 07:00 UTC, sokyrko commented on web_server/src/routes/invitation.rs
> +    Ok(result)
let result = records.into_iter().map(Invitation::from).collect()

2023-10-06 07:00 UTC, sokyrko commented on web_server/src/routes/appointment.rs
> +            ).await;
No need to wait for each particular IO action in the loop. Use `futures::future::join_all` or `futures::future::try_join_all`.

2023-10-06 07:00 UTC, sokyrko commented on web_server/src/routes/appointment.rs
> +            ).await;
Also note that you did not handle an error here.

2023-10-06 07:00 UTC, sokyrko commented on web_server/src/routes/appointment.rs
> +            let res = qr_client_clone.get_short_url(id.to_string()).await.unwrap();
This `unwrap` is not safe, as you may have an error due to network issues

2023-10-06 07:00 UTC, sokyrko commented on tickets_cli/src/main.rs
> +            todo!();
Are you going to store creds here?

2023-10-06 07:00 UTC, sokyrko commented on shared/src/domain/uri.rs
> +pub struct Uri(String);
Why not https://crates.io/crates/url ?
They have `serde` feature as well.

2023-10-06 07:00 UTC, sokyrko commented on shared/src/domain/email.rs
> +pub struct Email(String);
See https://docs.rs/nutype/latest/nutype/

2023-10-06 07:47 UTC, pahoma commented on tickets_cli/src/main.rs
> +            todo!();
No, it was an Idea to get JWT and set it on demand.

2023-10-06 15:48 UTC, pahoma commented on README.md
> +- `Init`: Initializes the connection to the database and executes migrations.
fixed

2023-10-06 22:01 UTC, danik-tro approved these changes

2023-10-06 22:01 UTC, danik-tro commented on shared/src/qr_client.rs
> +        let image = code.render::<Luma<u8>>().build();
Looks like it may block asynchronous IO. 
Perhaps, it should be done with tokio::task::spawn_blocking

2023-10-06 22:01 UTC, danik-tro commented on web_server/src/routes/invitation.rs
> +    }
I guess, you've already run Clippy

```rust
if appointment_id.is_some() { ... }
```

And looks like, you can get rid of this statement into something like this:

```rust
let records: Vec<DBInvitation> = if let Some(id) = appointment_id {
        query.push_str(" WHERE id = $1 ");
        sqlx::query_as::<_, DBInvitation>(&query)
            .bind(id)
            .fetch_all(pool).await?
    } else {
        sqlx::query_as::<_, DBInvitation>(&query)
            .fetch_all(pool).await?
    };
```

2023-10-07 12:35 UTC, vni commented on README.md
> +###Validation
add space after ###

2023-10-07 12:35 UTC, vni commented on README.md
> +#Event Appointments Service
add space after #

2023-10-07 12:35 UTC, vni commented on tickets_cli/Cargo.toml
> +lazy_static = "1.4.0"
maybe some day you will consider using LazyCell from rust std (it's not stabilized yet).
https://doc.rust-lang.org/stable/std/cell/struct.LazyCell.html

2023-10-07 12:35 UTC, vni commented on tickets_cli/src/appointment/delete.rs
> +pub async fn read_uuids() -> io::Result<Vec<Uuid>> {
hint and optional:
for me it looks strange that reading uuids from command line input is placed in the ```delete``` module.
Because this function is public.
If it were private I would understand that it is used only by ```delete_appointment_handler``` and it is auxiliary though.

2023-10-07 12:35 UTC, vni commented on tickets_cli/src/main.rs
> +                    send_invitation_letter_handler(appt_id, email).await.unwrap()
better use ```map_err(|e| return ... )``` and propagate errors up to main instead of  using ```.unwrap()``` and panicking. Even for programmers is somewhat frustrating to see the command-line-app gets crashed with a panic and a backtrace.

2023-10-07 12:35 UTC, vni commented on tickets_cli/src/appointment/send.rs
> +    let configuration = get_configuration().unwrap();
please, return error.

2023-10-07 12:35 UTC, vni commented on tickets_cli/src/appointment/generate.rs
> +    let configuration = get_configuration().unwrap();
```unwrap```.

2023-10-07 12:35 UTC, vni commented on tickets_cli/src/appointment/create.rs
> +/// Reads a single line of input from stdin asynchronously.
причеплюсь, на твій розсуд:
add note about trimmed input
also read_line is not a great name, cause the std:: has one.
you can rename it to read_trimmed_line

2023-10-07 12:35 UTC, vni commented on tickets_cli/src/appointment/create.rs
> +                println!("Invalid format. Please enter either `online` or `offline`.");
[0 || online ] [ 1 || offline ]
Btw: I don't see where "online" || "offline" are handled.

2023-10-07 12:35 UTC, vni commented on tickets_cli/src/appointment/create.rs
> +async fn read_uri_input(format: &AppointmentFormat, prompt: &str) -> Option<Url> {
I'm a little bit puzzled with URI and URL here.
(I know there are some subtle differences, but not in my head right now).

You accept URI from user. Parse it as URL, call it URI and return it, but name it URL in return type.
Looks like it is a point of confusion. And maybe not only for me.

2023-10-07 15:07 UTC, tiamo requested changes

2023-10-07 15:07 UTC, tiamo commented on tickets_cli/src/appointment/send.rs
> +    Ok(format!("Generated invintations: {:?}", invitations))
typo `inviNtations`

2023-10-07 15:07 UTC, tiamo commented on tickets_cli/src/appointment/send.rs
> +    sorted_emails.sort();
is it rly need to sort? )

2023-10-07 15:07 UTC, tiamo commented on tickets_cli/src/appointment/send.rs
> +    task::spawn_blocking(|| {
Can be implemented without blocking using `tokio::io::stdin`

2023-10-07 15:07 UTC, tiamo commented on configuration/development.yaml
It's better to add this to `gitignore`

2023-10-07 15:07 UTC, tiamo commented on configuration/production.yaml
and this

2023-10-07 15:07 UTC, tiamo commented on migrations/20230930132154_init.sql
> +    duration BIGINT NOT NULL,
Does `bigint` really need to be used here?

2023-10-07 15:07 UTC, tiamo commented on Dockerfile
> +FROM alpine:3 AS runtime
you can use smaller runtime image for `musl`

2023-10-07 15:07 UTC, tiamo commented on shared/Cargo.toml
> +once_cell = "1.18.0"
this is not a dev dependency

2023-10-07 15:07 UTC, tiamo commented on shared/Cargo.toml
> +claims = "0.7.1"
and probably this

2023-10-07 15:07 UTC, tiamo commented on shared/src/db.rs
> +pub async fn initialize() -> Result<PgPool,  Error> {
it's probably app initialisation, not just DB... and you call `get_configuration` twice

2023-10-07 15:07 UTC, tiamo commented on shared/src/email_client.rs
> +impl EmailClient {
probably better to use `builder` pattern here

2023-10-07 15:07 UTC, tiamo commented on tickets_cli/src/appointment/generate.rs
> +    let response = client.post(format!("{}/api/appointment/{}/invitation?count={}", web_url, appt_id, count))
It's better to create external `ApiClient` and use it for all api calls

2023-10-07 15:07 UTC, tiamo commented on web_server/Cargo.toml
> +once_cell = "1.18.0"
no dev

2023-10-07 15:07 UTC, tiamo commented on web_server/src/routes/appointment.rs
> +                let email_template  = include_str!("./../templates/email.html");
better to use `template_path` here or create some `render` function

2023-10-07 15:07 UTC, tiamo commented on web_server/src/routes/appointment.rs
> +    let mut query_builder = QueryBuilder::new("INSERT INTO invitation (id, appointment_id, short_url) ");
a lot of logic in the routes... it’s better to create some kind of services or repositories for this

2023-10-07 15:07 UTC, tiamo commented on web_server/src/routes/invitation.rs
> +    let qr_template  = include_str!("./../templates/qr.html");
`template_path` or an external function for rendering html

2023-10-07 15:07 UTC, tiamo commented on web_server/src/main.rs
> +    let qr_client = QRClient::new(
probably better to use something like this
```rust
QRClient::new(configuration.qr_client)
```

2023-10-07 17:22 UTC, vni commented on web_server/src/routes/invitation.rs
> +pub async fn get_invitation_qr(
all this routes down below can be private.
You add them to routing in the invitation_routes, so outside crates doesn't need them to be public.

2023-10-07 17:22 UTC, vni commented on web_server/src/routes/invitation.rs
> +    let records: Vec<DBInvitation> = if let Some(id) = appointment_id {
you can move ```query.push_str(" WHERE id = $1 ");``` under this if.

2023-10-07 17:22 UTC, vni commented on tickets_cli/src/appointment/create.rs
> +            "offline" => return AppointmentFormat::OFFLINE,
You can use "0" | "online"  => ...   and      "1" | "offline" => ... notation

2023-10-07 17:22 UTC, vni commented on web_server/src/routes/appointment.rs
>          query.push_str(" WHERE id = $1 ");
you can move it under ```let records: .... if ```

2023-10-07 17:54 UTC, vni commented on shared/src/domain/email.rs
> +impl From<String> for Email {
If conversion can fail, it's better to use ```TryFrom``` trait.

2023-10-08 09:04 UTC, sokyrko commented on web_server/src/routes/validation.rs
> +    tracing::info!("{} {} {}",  invitation.date.date(), yesterday.date(), invitation.date < yesterday);
Consider using structures logging instead formatting strings

2023-10-08 09:06 UTC, sokyrko commented on web_server/src/routes/validation.rs
> +                .append_header((http::header::LOCATION, invitation.link.unwrap().into_inner()))
```
invitation.link.expect("Can't extract invitation url")
```
-->
```
invitation.link.expect("Link always exists for online events")
```

2023-10-08 09:07 UTC, sokyrko commented on web_server/src/routes/appointment.rs
> +            match qr_client_clone.get_short_url(id.to_string()).await {
Try this:
qr_client_clone.get_short_url(id.to_string()).await.map(|res| (id, res.short_url))

2023-10-08 09:10 UTC, sokyrko approved these changes

2023-10-08 22:40 UTC, tiamo commented on tickets_cli/src/appointment/send.rs
> +    let mut reader = BufReader::new(io::stdin());
This code can be simplified

```rust
let mut lines = BufReader::new(io::stdin()).lines();
let mut emails = Vec::new();

while let Ok(Some(line)) = lines.next_line().await {
    if line.trim().is_empty() {
        break;
    }
    let email = Email::parse(line)
        .map_err(|_| io::Error::new(ErrorKind::InvalidData, "Failed to parse Email"))?;
    emails.push(email);
}

// ...
```

2023-10-08 22:40 UTC, tiamo commented on web_server/src/routes/mod.rs
> +const QR_TEMPLATE_PATH: &str = "./../templates/qr.html";
It is unnecessary to create such constants, move base path `./../templates` to `render_template` and use just template file names

2023-10-09 06:19 UTC, pahoma commented on tickets_cli/src/appointment/send.rs
> +    let mut reader = BufReader::new(io::stdin());
Yeah! Looks nice. Thx

2023-10-09 14:18 UTC, vni commented on tickets_cli/src/appointment/send.rs
> +// }
Ummm, commented code?

2023-10-09 14:18 UTC, vni commented on tickets_cli/src/appointment/send.rs
> +        .into_iter().collect::<HashSet<_>>().into_iter().collect();
Better leave it as it were.

Creating a HashSet and then again creating a Vec is not a good idea of introducing additional allocations... :)

2023-10-10 08:24 UTC, vni approved these changes

2023-10-10 11:15 UTC, tiamo approved these changes
👍

2023-10-11 07:26 UTC, pahoma commented
Thanks a lot for your time guys. I really appreciate it. First merge

2023-10-11 07:26 UTC, merged